name: release
on:
  push:
    branches: [main]

permissions:
  contents: write             # allow tag + release
  pull-requests: write        # allow the bot to open/refresh PRs
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          # Use the default GITHUB_TOKEN with proper permissions
          token: ${{ github.token }}



          
